### ISSUE TITLE
NGINX_APP_PLUGIN is not located in the plugin directory. Nothing to install...

### ISSUE THREAD

**Issue by Able2Code** [openbridge/wordpress#1]
Hi, @tspicer , by using config showed in the readme i see this
`"NGINX_APP_PLUGIN=wordpress"`
but the php-fpm container can't locate it, where can i download ?
php-fmp logs also show error like:
<pre>
ALERT: oops, unknown child (603) exited with code 0. Please open a bug report (https://bugs.php.net).
</pre>
Thank you in advance !

**Comment by tspicer** [comment]
Hi,
This doc is used as the support doc for our AWS Marketplace image:
https://aws.amazon.com/marketplace/pp/B07FCV1BPF

By setting `NGINX_APP_PLUGIN=wordpress` the system is looking for `/usr/src/plugins/$NGINX_APP_PLUGIN/install`. Since you do not have  an`install` file present it will fail.  However, you can create your own `install` WP installer. You can write a bash installer script and then have it run and pre-install everything for you. There are resources online that describe the process.

```
function install_plugin() {

if [[ ! -d /usr/src/plugins/$NGINX_APP_PLUGIN ]]; then
  echo "INFO: NGINX_APP_PLUGIN is not located in the plugin directory. Nothing to install..."
else
  echo "OK: Installing NGINX_APP_PLUGIN=$NGINX_APP_PLUGIN..."
  chmod +x /usr/src/plugins/$NGINX_APP_PLUGIN/install
  runplugin="/usr/src/plugins/$NGINX_APP_PLUGIN/install" && /bin/bash -c "${runplugin}"
fi

}
```
Also, you can simply use the AMI we created and it does everything for you. :)

**Comment by Able2Code** [comment]
Ok perfect, as i thought, i' m running an ec2 instance to see which plugins you install by default, on wp. Thank you !
