### ISSUE TITLE
WooCommerce Caching Problems

### ISSUE THREAD

**Issue by samex** [openbridge/wordpress#13]
Hi,

everything working fine except woocommerce cart functions. I cant edit cart, add and remove new items. I tried several caching plugins to exclude these site from caching but I think the nginx container is ignoring this.

So my question for now is, how I disable cache for specific subpages or queries in the nginx config files?

Regards

**Comment by tspicer** [comment]
I don't know your specific configuration, but I would no expect plugins to work because the cache is occurring at a lower level.

As you suggested the approach would be to use Nginx location associated with woocommerce to turn off caching. You can take a look at https://github.com/openbridge/nginx or http://nginx.org/en/docs/ for guidance.

You may want to explore the built-in mappings:
https://github.com/openbridge/nginx/blob/561279fbcaafe110b7f88e990b9a7086a8c1a2b0/conf/html/nginx/map.d/nocache/nocache.map

Setting up a skip cache, cache bypass or mapping would likely be the place to explore in your config. Good luck

**Comment by samex** [comment]
Thanks,

what is the number behind the expression standig for? 

i.e. :
~*\/wp-admin\/.* 3;

**Comment by tspicer** [comment]
Take a look at various Nginx docs for reference. For example, http://nginx.org/en/docs/http/ngx_http_map_module.html
